# Generated by Django 5.0 on 2023-12-13 16:55

import apps.products.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('description', models.TextField()),
                ('measure', models.CharField(choices=[('kg', 'kg'), ('litr', 'litr'), ('dona', 'dona'), ('gr', 'gr'), ('metr', 'metr')], max_length=15)),
                ('barcode', models.CharField(max_length=31)),
                ('price', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to=apps.products.models._generate_filename)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
            ],
        ),
    ]
