# Generated by Django 5.0 on 2024-04-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('discount', models.IntegerField(default=0)),
                ('cash', models.IntegerField(default=0)),
                ('without_cash', models.IntegerField(default=0)),
                ('total_summa', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('amount', models.FloatField(default=0)),
                ('total', models.IntegerField()),
            ],
        ),
    ]
