# Generated by Django 5.0 on 2024-02-15 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sales', '0003_sale_store_sale_user'),
        ('smenas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='smena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='smenas.smena'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
