# Generated by Django 5.0 on 2023-12-19 04:01

from django.db import migrations, models

import apps.categories.models


class Migration(migrations.Migration):
    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.categories.models._generate_filename),
        ),
    ]
