# Generated by Django 5.0 on 2023-12-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashboxes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashboxpermission',
            name='cashbox',
        ),
        migrations.RemoveField(
            model_name='cashboxpermission',
            name='session',
        ),
        migrations.RemoveField(
            model_name='cashboxpermission',
            name='user',
        ),
        migrations.AddField(
            model_name='cashbox',
            name='end_date',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashbox',
            name='start_date',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='CashboxPermission',
        ),
    ]
