# Generated by Django 5.0 on 2023-12-25 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashboxes', '0002_remove_cashboxpermission_cashbox_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashbox',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='cashbox',
            name='device_name',
        ),
        migrations.RemoveField(
            model_name='cashbox',
            name='expire_date',
        ),
        migrations.AddField(
            model_name='cashbox',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
