# Generated by Django 5.0 on 2023-12-24 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_manager_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.JSONField(blank=True, null=True)),
                ('device_id', models.CharField(default='', max_length=31)),
                ('is_active', models.BooleanField(default=True)),
                ('expire_date', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
