# Generated by Django 5.0 on 2023-12-24 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_seans'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seans',
            old_name='user_id',
            new_name='user',
        ),
    ]
