# Generated by Django 5.0 on 2023-12-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0006_rename_user_id_seans_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(default=' ', upload_to='user/images'),
            preserve_default=False,
        ),
    ]
