# Generated by Django 5.0 on 2024-01-07 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
