# Generated by Django 5.0 on 2024-01-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_delete_manager_delete_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seans',
            name='device_id',
            field=models.CharField(default='', max_length=127),
        ),
    ]
