# Generated by Django 5.0 on 2024-01-14 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_usertarif'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTarif',
        ),
    ]
