# Generated by Django 5.0 on 2024-04-14 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recovery', '0002_initial'),
        ('smenas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recovery',
            name='smena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smenas.smena'),
        ),
    ]
