# Generated by Django 5.0 on 2024-02-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smenas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smena',
            name='cash',
            field=models.IntegerField(default=0),
        ),
    ]
