# Generated by Django 5.0 on 2023-12-20 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stores', '0001_initial'),
        ('users', '0004_manager_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_manager': True}, on_delete=django.db.models.deletion.CASCADE,
                                    to='users.manager'),
        ),
    ]
